### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by jedie** [eGenix/egenix-pyrun#13]
```
Traceback (most recent call last):
  File "<pyrun>/pyrun3.11.py", line 52, in <module>
  File "<pyrun>/pyrun_main.py", line 912, in pyrun_main
  File "<pyrun>/pyrun_main.py", line 813, in pyrun_execute_script
  File "<stdin>", line 1, in <module>
  File "/tmp/pyruntest/lib/python3.11/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "/tmp/pyruntest/lib/python3.11/site-packages/psycopg/pq/__init__.py", line 19, in <module>
    from .misc import ConninfoOption, PGnotify, PGresAttDesc
  File "/tmp/pyruntest/lib/python3.11/site-packages/psycopg/pq/misc.py", line 13, in <module>
    import ctypes.util
  File "<pyrun>/ctypes/__init__.py", line 8, in <module>
ModuleNotFoundError: No module named '_ctypes'
```

script to test this:
```
#!/bin/bash

set -e

VERSION=3.11

PYRUN=~/.local/bin/pyrun${VERSION}

${PYRUN} -V
${PYRUN} -m venv --without-pip /tmp/pyruntest

ls -la /tmp/pyruntest/bin
/tmp/pyruntest/bin/pyrun${VERSION} -V

# pyrun error: Could not run 'ensurepip': No module named ensurepip
#/tmp/pyruntest/bin/pyrun${VERSION} -m ensurepip

# pyrun error: Could not run 'pip': No module named pip
# /tmp/pyruntest/bin/pyrun${VERSION} -m pip install --upgrade pip

cd /tmp
wget --timestamp https://bootstrap.pypa.io/get-pip.py

/tmp/pyruntest/bin/pyrun${VERSION} /tmp/get-pip.py

/tmp/pyruntest/bin/pyrun${VERSION} -m pip -V
/tmp/pyruntest/bin/pyrun${VERSION} -m pip install --upgrade pip

/tmp/pyruntest/bin/pyrun${VERSION} -m pip install -U psycopg[binary]

/tmp/pyruntest/bin/pyrun${VERSION} -c "import psycopg; print(psycopg.__version__)"
```

**Comment by malemburg** [comment]
The ctypes module is currently not built directly into the pryrun executable, but only as a shared lib. You can find the needed shared lib in the distribution archives under lib/python3.11/lib-dynlib/,

Copying the lib-dynlib/ dir to /tmp/pyruntest/ should get things working. If you only need ctypes, you can also copy the _ctypes*.so file into the same dir where pyrun3.11 lives. This should normally also work.

I'm a bit hesitant to include ctypes into the pyrun binary, since this introduces external dependencies on libffi, which may not be available everywhere (but I'm happy to be proven wrong on that one).

**Comment by malemburg** [comment]
> What does https://github.com/indygreg/python-build-standalone/ do in this direction?

It seems to include a statically linked version into the binary.

I checked on various systems I have access to:
- I found three different versions of libffi (6, 7, and 8)
- some systems did not have the lib at all

This makes it a rather poor candidate for inclusion as a shared dependency.

I could investigate statically linking again libffi. It's a rather small lib, so this may be an option.
Statically linking against libffi would fix this, but also add between 600-700kB uncompressed to the pyrun binary.
