### ISSUE TITLE
AssertionError: <pyrun>/distutils/core.py

### ISSUE THREAD

**Issue by jedie** [eGenix/egenix-pyrun#3]
I just try pyrun 3.9 with tox...

I have download https://github.com/eGenix/egenix-pyrun/releases/download/egenix-pyrun-2.5.0/egenix-pyrun-2.5.0-py3.9_ucs4-linux-x86_64.tgz and extract only `pyrun3.9` from `./bin/` and store it as: `/.local/bin/python3.9` and call tox.

I ran into this error:
```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "<pyrun>/pyrun3.9.py", line 52, in <module>
        File "<pyrun>/pyrun_main.py", line 912, in pyrun_main
        File "<pyrun>/pyrun_main.py", line 789, in pyrun_execute_script
        File "<pyrun>/pyrun_main.py", line 78, in pyrun_exec_code_file
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "<pyrun>/importlib/__init__.py", line 127, in import_module
        File "<pyrun>/importlib/_bootstrap.py", line 1039, in _gcd_import
        File "<pyrun>/importlib/_bootstrap.py", line 1016, in _find_and_load
        File "<pyrun>/importlib/_bootstrap.py", line 981, in _find_and_load_unlocked
        File "<pyrun>/importlib/_bootstrap.py", line 228, in _call_with_frames_removed
        File "<pyrun>/importlib/_bootstrap.py", line 1039, in _gcd_import
        File "<pyrun>/importlib/_bootstrap.py", line 1016, in _find_and_load
        File "<pyrun>/importlib/_bootstrap.py", line 995, in _find_and_load_unlocked
        File "<pyrun>/importlib/_bootstrap.py", line 680, in _load_unlocked
        File "<pyrun>/importlib/_bootstrap_external.py", line 850, in exec_module
        File "<pyrun>/importlib/_bootstrap.py", line 228, in _call_with_frames_removed
        File "/tmp/pip-build-env-4y70yxj7/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/home/jens/foobar/bx_django_utils/.tox/py39-django42/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: <pyrun>/distutils/core.py
      [end of output]
```

**Comment by malemburg** [comment]
This is a bug in or with the distutils hack in setuptools.

The standard work-around for this is to define the OS env var `` `SETUPTOOLS_USE_DISTUTILS=stdlib` for Python 3.8 and 3.9.

We won't fix this in PyRun, since it's better to use setuptools directly anyway.
